# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=255)),
                ('rg', models.CharField(max_length=255)),
                ('nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=255)),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=255)),
                ('complemento', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
            ],
        ),
    ]
